cmake: Autospec creation for update from version 3.24.2 to version 3.24.3
Brad King (18):
      cmStringAlgorithms: Add functions to parse strings to long long integers
      file: Avoid strange istringstream crash in cmake.org binaries on Alpine Linux
      Xcode: Drop CMAKE_INTDIR= definition in Swift targets
      Tests: Update RunCMake.XcodeProject iOS cases for Xcode 14.0
      gitlab-ci: update macOS jobs to use Xcode 14.0
      CMake 3.23.4
      COMPILE_WARNING_AS_ERROR: Fix internal formatting of options table
      LLVMFlang: Add support for mixed-language linking with Fortran
      Help: Add versionadded for string(TIMESTAMP) %f specifier
      try_compile: Honor CMP0128 setting in test project
      Tests: Explicitly allow usage of git file-based protocol in test cases
      cm/filesystem: Fix crash with pre-C++11 std::string GNU ABI in C++17
      Tests: Avoid running C++11 test on GNU < 4.7
      VS: Fix crash finding vswhere on 32-bit Windows
      Ninja: Restore support for non-ascii paths on Windows with ninja<=1.10
      Tests: Add case for ninja with non-ascii chars
      CMake 3.23.5
      CMake 3.24.3

Erlend E. Aasland (1):
      CPack/IFW: Add support for QtIFW 4.4

Kyle Edwards (1):
      CPack: Require no argument for --trace and --trace-expand

Marc Chevrier (1):
      Apple: Fix regression when linking a framework with postfix

Michael Hirsch (3):
      FindMatlab: Add MEX binary file suffix for Apple Silicon native Matlab
      FindMatlab: add R2022b 9.13 version map
      Intel/IntelLLVM: Fortran has distinct "-Werror"-like flag

Mika Fischer (1):
      CPack/NSIS: Fix installer not waiting for uninstaller to finish

Robert Maynard (1):
      CUDA: Add support for the two new architectures in 11.8

Sergiu Deitsch (2):
      FindJNI: replace CMAKE_ANDROID_API by CMAKE_SYSTEM_VERSION
      Android: Avoid searching API level directories matching architecture bitness

Zack Galbreath (1):
      ctest: only report make-level errors when no others are found

مهدي شينون (Mehdi Chinoune) (2):
      LLVMFlang: Add support for Windows
      LLVMFlang: Add a required line to define linking rules on Windows